- name: Creates backend app directory
  become: true
  file:
    path: /home/ubuntu/web
    state: directory

- name: Unarchive backend files
  become: true
  unarchive:  
    src: artifact.tar.gz
    dest: /home/ubuntu/web

- name: "Executing Node app with PM2"
  become: true
  shell: |
    cd /home/ubuntu/web/dist
    npm install
    pm2 stop default
    pm2 start npm -- start
    pm2 start main.js
    
- name: "generate start up script to start pm2 on ec2 restarts"
  become: true
  shell: | 
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save --force
    